language: node_js
sudo: false
node_js:
- 'stable'
env:
  matrix:
  - SAUCE_USERNAME=jsfc
  global:
    secure: RXiNhz5ga4fIaXYfs7UfSH6FHdo3yPm1KMvrY82Ra5qhVmPNDTBEVDAHZOKGHW61Fiso5xZhkVMMSJtBhDIspMgvRGrKzbTGaHnDjufEC2Lm4vu67nDt1zgyoNt9zqv3RRzxh+kTZl/FzWvv0JJUnURtx6CqJThXGcjFAs3W3/Y=
